-- TODO Add indexes for foign keys and coordinates

CREATE SCHEMA IF NOT EXISTS private;
CREATE TABLE IF NOT EXISTS private.__ef_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___ef_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE SCHEMA IF NOT EXISTS private;

CREATE TABLE private.games (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    size integer NOT NULL,
    init boolean NOT NULL,
    ended boolean NOT NULL,
    finished boolean NOT NULL,
    CONSTRAINT "PK_games" PRIMARY KEY (id)
);

CREATE TABLE private.ships (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    game_id bigint NOT NULL,
    x_start integer NOT NULL,
    x_end integer NOT NULL,
    y_start integer NOT NULL,
    y_end integer NOT NULL,
    CONSTRAINT "PK_ships" PRIMARY KEY (id),
    CONSTRAINT "FK_ships_games_game_id" FOREIGN KEY (game_id) REFERENCES private.games (id) ON DELETE CASCADE
);

CREATE TABLE private.shots (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    game_id bigint NOT NULL,
    ship_id bigint NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    CONSTRAINT "PK_shots" PRIMARY KEY (id),
    CONSTRAINT "FK_shots_games_game_id" FOREIGN KEY (game_id) REFERENCES private.games (id) ON DELETE CASCADE,
    CONSTRAINT "FK_shots_ships_ship_id" FOREIGN KEY (ship_id) REFERENCES private.ships (id) ON DELETE RESTRICT
);

CREATE INDEX "IX_ships_game_id" ON private.ships (game_id);

CREATE INDEX "IX_shots_game_id" ON private.shots (game_id);

CREATE INDEX "IX_shots_ship_id" ON private.shots (ship_id);

INSERT INTO private.__ef_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20210314093135_Init', '5.0.4');

COMMIT;